### ISSUE TITLE
Making a single .html of the examples (resources embedded)???

### ISSUE THREAD

**Issue by slycooper724** [fabiofenoglio/lelo-f1-web-sdk#1]
Hello, I was wondering if there was any way there could be a offline version compiled for this. The ideal output would be a simple .html file with all the resources embedded into the file. I tried doing this multiple ways and haven't been met with much success. I really think this is an impressive implementation of the SDK, and would like to use this in a more portable/offline fashion since this is way better than the demo app, and being able to use a browser is genius.
Best Regards,
- Sly

**Comment by fabiofenoglio** [comment]
Hello! Are you referring to one of the samples in particular? There are three different at the moment.
I can try to bundle it for you.

**Comment by slycooper724** [comment]
Thanks for your prompt reply!
I was referring to the mobile-example specifically, but it would be nice to have an html file for each variation.
On a sidenote, I was hoping to make a portable peer-to-peer remote access html file that could be hosted as one complete package (or opened as a file in web browsers). I found some code regarding Mutation Observers + WebSocket [here](https://www.html5rocks.com/en/tutorials/streaming/screenshare/), but its so old and undocumented that I do not know if it would work anymore, or if the implementation is obsolete. I didn't like the idea of needing a node.js server for the Mutation Observer. I want this to be both a client and host, with a main menu for selecting client and host modes. The host mode would have a footer with information regarding connecting a client in the case of a partner being able to control the F1 (IP Address [Some remote access apps for other toys reveal this so this isn't really a concern for me], Authentication details, etc.), and the client would immediately prompt for this information and connect to the host. I do not know if this possible, but it seems like it could work.
Best Regards,
- Sly

**Comment by fabiofenoglio** [comment]
Hi,
actually this repository is meant to provide a client library, and the presence of the demo webapp just serves as an example. However, I plan on moving the sample to its own repository to make a standalone webapp out of it.
The problem of offline usage could be addressed by combining webpack bundling with a service worker with aggresive caching option.

I plan on opening this repository in these days and will update you when it'll be available so we can work on your suggestions there!

**Comment by fabiofenoglio** [comment]
Hello @slycooper724 
since I've got many requests about remote control and similar features, I setup a public hub to share and collaborate on F1 SDK applications.

You can register and start using the BETA version here: https://lelo-hub.fabiofenoglio.it/
Note: since it is based on Web Bluetooth it requires Chrome or Chrome on mobile.

I'd like to ask you if you could kindly open an issue detailing your desiderata (es. remote control, particular control features, interface enhancements, ...) on this other repository: https://github.com/fabiofenoglio/lelo-f1-hub/issues

Thank you for your cooperation!
